services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    image: scraper
    container_name: php
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - laravel

  redis:
    image: redis:latest
    command: redis-server --appendonly yes --requirepass "${REDIS_PASSWORD}"
    container_name: redis
    restart: unless-stopped
    ports:
        - 6379:6379
    networks:
      - laravel

  queue:
      container_name: queue
      build:
          context: .
          dockerfile: docker/php/Dockerfile
      image: scraper
      volumes:
          - .:/var/www
      command: php artisan queue:work
      networks:
          - laravel

networks:
  laravel:
    driver: bridge
